//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01_01
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TEL_USL_01_01Entities : DbContext
    {
        private static TEL_USL_01_01Entities _instance;
        public TEL_USL_01_01Entities()
            : base("name=TEL_USL_01_01Entities")
        {
        }

        public static TEL_USL_01_01Entities GetContext()
        {
            if (_instance == null) _instance = new TEL_USL_01_01Entities();
            return _instance;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Reg> Reg { get; set; }
        public virtual DbSet<Schet> Schet { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USl> USl { get; set; }
    }
}
